name: "Gitea Release Action"
description: "A Gitea Action to manage Gitea release"
inputs:
  files:
    description: "The files needs to be uploaded"
    required: true
  api_key:
    description: "The access token to interact with Gitea"
    required: false
    default: ${{ github.token }}
outputs:
  status:
    description: "The upload status"
runs:
  using: "go"
  main: "main.go"
